// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XUnitTest.Mvc.Data.Context;

#nullable disable

namespace XUnitTest.Mvc.Migrations
{
    [DbContext(typeof(XUnitTestMvcDbContext))]
    [Migration("20240509133414_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.18");

            modelBuilder.Entity("XUnitTest.Mvc.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a6749f60-4616-427b-980b-51545683cda0"),
                            Color = "Red",
                            Name = "Product 1",
                            Price = 2000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("b02c1fb4-361f-42c4-a868-0c1b5b9f9a69"),
                            Color = "Black",
                            Name = "Product 2",
                            Price = 3000m,
                            Stock = 150
                        },
                        new
                        {
                            Id = new Guid("56aeb717-6761-4d10-be09-88c43a1f2d6b"),
                            Color = "Yellow",
                            Name = "Product 3",
                            Price = 4000m,
                            Stock = 200
                        },
                        new
                        {
                            Id = new Guid("13d11f29-8e5e-43e8-82ce-8f8c0fa2a4a3"),
                            Color = "Green",
                            Name = "Product 4",
                            Price = 5000m,
                            Stock = 250
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
